name: Check Reactor Core 3.6 SNAPSHOTS

on:
  schedule:
    - cron: "0 14 * * *"
permissions: read-all
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up JDK 1.8
        uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Gradle
        run: ./gradlew clean check --no-daemon -PforceTransport=nio -PreactorCoreVersion='3.6.5-SNAPSHOT' -PforceContextPropagationVersion='1.1.0'
